joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 3.73064127613788
    has_acceleration_limits: true
    max_acceleration: 28.1204132955748
  joint_2:
    has_velocity_limits: true
    max_velocity: 2.9845130209103
    has_acceleration_limits: true
    max_acceleration: 24.0036091957869
  joint_3:
    has_velocity_limits: true
    max_velocity: 3.3857642159438
    has_acceleration_limits: true
    max_acceleration: 29.5102015256453
  joint_4:
    has_velocity_limits: true
    max_velocity: 3.73064127613788
    has_acceleration_limits: true
    max_acceleration: 23.901804140518
  joint_5:
    has_velocity_limits: true
    max_velocity: 2.87060410727889
    has_acceleration_limits: true
    max_acceleration: 27.0439989326998
  joint_6:
    has_velocity_limits: true
    max_velocity: 5.96902604182061
    has_acceleration_limits: true
    max_acceleration: 38.2017666676519
  extruder:
    has_velocity_limits: false
    has_acceleration_limits: false
  tcp_joint:
    has_velocity_limits: true
    max_velocity: 5.96902604182061
    has_acceleration_limits: true
    max_acceleration: 38.2017666676519